package ALLEN_CODE;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author allen
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    String fullName, age, patientID; 
    public Login(String firstName, String lastName, String age, String PatientID) {
        this.fullName = firstName + " " + lastName;
        this.age = age;
        this.patientID = PatientID;
        initComponents();
        scaleImage();
        try {
            Connectivity();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
//    public Login(String PatientID) {
//        this.patientID = PatientID;
//        initComponents();
//        scaleImage();
//        try {
//            Connectivity();
//        } catch (SQLException ex) {
//            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
    public Login () {
        initComponents();
        scaleImage();
        try {
            Connectivity();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    Connection con;
    /* SQL Statement */
    Statement st;
    PreparedStatement pst;
    
    private static final String DBname = "maids_database";
    private static final String DBdriver = "com.mysql.cj.jdbc.Driver";
    private static final String DBurl = "jdbc:mysql://localhost:3306/" + DBname;
    private static final String DBIDNumber = "root"; 
    private static final String DBPassword = "";
    
    public void Connectivity() throws SQLException {
        
        try {
            Class.forName(DBdriver);
            con = DriverManager.getConnection(DBurl,DBIDNumber,DBPassword);
            st = con.createStatement();
            if (con != null) {
                System.out.println("Connection Successful");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    public void scaleImage () {
        ImageIcon icon = new ImageIcon("C:\\Users\\admin\\OneDrive\\Documents\\NetBeansProjects\\[FINAL] OOP\\src\\img\\MaidsLogin.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lbl_LogoLabel.getWidth(),lbl_LogoLabel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        lbl_LogoLabel.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_FirstName = new javax.swing.JTextField();
        pnl_logo = new javax.swing.JPanel();
        lbl_LogoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_IDText = new javax.swing.JLabel();
        txt_IDNumber = new javax.swing.JTextField();
        lbl_PasswordNotice = new javax.swing.JLabel();
        btn_loginSubmit = new javax.swing.JButton();
        pswrd_loginPassword = new javax.swing.JPasswordField();
        lbl_statusLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        txt_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FirstNameActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_logo.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout pnl_logoLayout = new javax.swing.GroupLayout(pnl_logo);
        pnl_logo.setLayout(pnl_logoLayout);
        pnl_logoLayout.setHorizontalGroup(
            pnl_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_LogoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
        pnl_logoLayout.setVerticalGroup(
            pnl_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_LogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DOCTOR");

        lbl_IDText.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_IDText.setText("Full Name");

        txt_IDNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDNumberActionPerformed(evt);
            }
        });

        lbl_PasswordNotice.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_PasswordNotice.setText("ID Number");

        btn_loginSubmit.setBackground(new java.awt.Color(172, 216, 230));
        btn_loginSubmit.setText("Login");
        btn_loginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginSubmitActionPerformed(evt);
            }
        });

        pswrd_loginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswrd_loginPasswordActionPerformed(evt);
            }
        });

        lbl_statusLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_statusLabel.setText("Please enter your credentials");
        lbl_statusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_statusLabel.setVerifyInputWhenFocusTarget(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");

        jButton1.setBackground(new java.awt.Color(172, 216, 230));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("<- Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_PasswordNotice)
                            .addComponent(btn_loginSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(pswrd_loginPassword)
                            .addComponent(txt_IDNumber)
                            .addComponent(lbl_IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lbl_statusLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(lbl_IDText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_IDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_PasswordNotice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswrd_loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_statusLabel)
                .addGap(18, 18, 18)
                .addComponent(btn_loginSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FirstNameActionPerformed

    private void txt_IDNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDNumberActionPerformed

    private void btn_loginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginSubmitActionPerformed
        String employeeFullName, IDNumber;
        
        employeeFullName = txt_IDNumber.getText();
        IDNumber = pswrd_loginPassword.getText();
        
        String queryLogin = "SELECT * FROM accountdetails WHERE accFull_Name = ? AND  accIDNumber = ?";
        
        try {
            pst = con.prepareStatement(queryLogin);
            pst.setString(1, employeeFullName);   
            pst.setString(2, IDNumber);  

            ResultSet rs = pst.executeQuery();

            if (!rs.next()) {
                lbl_statusLabel.setText("The entered credentials is invalid ");
                lbl_statusLabel.setForeground(Color.RED);
            } else {
                String firstName = rs.getString("accFirst_Name"); 
                String lastName = rs.getString("accLast_Name"); 
                String employeeName = firstName + " " + lastName;
                JOptionPane.showMessageDialog(null, "Welcome, " + employeeName + "!");
                MainInterface main = new MainInterface(employeeFullName, IDNumber, fullName, age, patientID);
                main.setLocationRelativeTo(null);
                main.setResizable(false);
                main.setTitle("Main Interface");
                this.dispose();
                main.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }     

    }//GEN-LAST:event_btn_loginSubmitActionPerformed

    private void pswrd_loginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswrd_loginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswrd_loginPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                TempMenu main = new TempMenu();
                main.setLocationRelativeTo(null);
                main.setResizable(false);
                this.dispose();
                main.setTitle("Nurse Menu");
                main.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login main = new Login();
                main.setLocationRelativeTo(null);
                main.setResizable(false);
                main.setTitle("Doctor Login");
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_loginSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_IDText;
    private javax.swing.JLabel lbl_LogoLabel;
    private javax.swing.JLabel lbl_PasswordNotice;
    private javax.swing.JLabel lbl_statusLabel;
    private javax.swing.JPanel pnl_logo;
    private javax.swing.JPasswordField pswrd_loginPassword;
    private javax.swing.JTextField txt_FirstName;
    private javax.swing.JTextField txt_IDNumber;
    // End of variables declaration//GEN-END:variables
}
