package ALLEN_CODE;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.ResultSet;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author allen
 */
public class TempMenu extends javax.swing.JFrame {

    /**
     * Creates new form TempMenu
     */
    String fullName, IDNumber;

    public TempMenu(String FullName, String iDNumber) {
        this.fullName = FullName;
        this.IDNumber = iDNumber;
        initComponents();
        scaleImage();
        try {
            Connectivity();
        } catch (SQLException ex) {
            Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public TempMenu() {
        initComponents();
        scaleImage();
        try {
            Connectivity();
        } catch (SQLException ex) {
            Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void scaleImage() {
        ImageIcon icon = new ImageIcon("C:\\Users\\admin\\OneDrive\\Documents\\NetBeansProjects\\[FINAL] OOP\\src\\img\\MaidsLogin.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lbl_Logo.getWidth(), lbl_Logo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        lbl_Logo.setIcon(scaledIcon);

        ImageIcon icon1 = new ImageIcon("C:\\Users\\admin\\OneDrive\\Documents\\NetBeansProjects\\[FINAL] OOP\\src\\img\\IconMaids.png");
        Image img1 = icon1.getImage();
        Image imgScale1 = img1.getScaledInstance(lbl_Icon.getWidth(), lbl_Icon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon1 = new ImageIcon(imgScale1);
        lbl_Icon.setIcon(scaledIcon1);
    }

    Connection con;
    /* SQL Statement */
    Statement st;
    PreparedStatement pst;
    
    private static final String DBname = "maids_database";
    private static final String DBdriver = "com.mysql.cj.jdbc.Driver";
    private static final String DBurl = "jdbc:mysql://localhost:3306/" + DBname;
    private static final String DBIDNumber = "root"; 
    private static final String DBPassword = "";
    
    public void Connectivity() throws SQLException {
        
        try {
            Class.forName(DBdriver);
            con = DriverManager.getConnection(DBurl,DBIDNumber,DBPassword);
            st = con.createStatement();
            System.out.println("Connection Successful DEBUG");
            if (con != null) {
                System.out.println("Connection Successful");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_maidsDef1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_Logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_newPatient = new javax.swing.JButton();
        btn_oldPatient = new javax.swing.JButton();
        lbl_maidsDef = new javax.swing.JLabel();
        lbl_maidsDef2 = new javax.swing.JLabel();
        lbl_maidsDef3 = new javax.swing.JLabel();
        lbl_Icon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_logOut = new javax.swing.JButton();

        lbl_maidsDef1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbl_maidsDef1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_maidsDef1.setText("MEDICAL ASSISTANT");
        lbl_maidsDef1.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 31, 97));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        btn_newPatient.setBackground(new java.awt.Color(172, 216, 230));
        btn_newPatient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_newPatient.setText("New Patient");
        btn_newPatient.setBorder(null);
        btn_newPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newPatientActionPerformed(evt);
            }
        });

        btn_oldPatient.setBackground(new java.awt.Color(172, 216, 230));
        btn_oldPatient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_oldPatient.setText("Old Patient");
        btn_oldPatient.setBorder(null);
        btn_oldPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oldPatientActionPerformed(evt);
            }
        });

        lbl_maidsDef.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_maidsDef.setForeground(new java.awt.Color(255, 255, 255));
        lbl_maidsDef.setText("MEDICAL ASSISTANT");
        lbl_maidsDef.setToolTipText("");

        lbl_maidsDef2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_maidsDef2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_maidsDef2.setText("IDENTIFICATION SYSTEM");
        lbl_maidsDef2.setToolTipText("");

        lbl_maidsDef3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_maidsDef3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_maidsDef3.setText("MAIDS");
        lbl_maidsDef3.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Is the Patient");

        btn_logOut.setBackground(new java.awt.Color(172, 216, 230));
        btn_logOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_logOut.setText("Log out");
        btn_logOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_maidsDef)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_oldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_newPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_maidsDef2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_maidsDef3)
                            .addComponent(lbl_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_maidsDef3)
                .addGap(4, 4, 4)
                .addComponent(lbl_maidsDef, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_maidsDef2)
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btn_newPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_oldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btn_logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newPatientActionPerformed
        // TODO add your handling code here:
        Register main = new Register();
        this.dispose();
        main.setLocationRelativeTo(null);
        main.setResizable(false);
        main.setTitle("Register Patient Form");
        main.setVisible(true);
    }//GEN-LAST:event_btn_newPatientActionPerformed

    private void btn_oldPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oldPatientActionPerformed

        String caseNumber = JOptionPane.showInputDialog("Enter your patient ID :");

        if (caseNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Patient ID Required");
        } else {
            String queryData = "SELECT * FROM patientaccounts WHERE PatientID = ?";
            try {
                pst = con.prepareStatement(queryData);
                pst.setString(1, caseNumber);
                ResultSet rs = pst.executeQuery();
                
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "Patient ID NOT FOUND!");
                }
                else {
                    OldPatient main = new OldPatient(caseNumber);
                    this.dispose();
                    main.setLocationRelativeTo(null);
                    main.setResizable(false);
                    main.setTitle("Old Patient Form");
                    main.setVisible(true);
                }
            }
            catch (SQLException ex){
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btn_oldPatientActionPerformed

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
        LoginNurse main = new LoginNurse();
        this.dispose();
        main.setLocationRelativeTo(null);
        main.setResizable(false);
        JOptionPane.showMessageDialog(this, "Logged Out Successfully");
        main.setTitle("Register Patient Form");
        main.setVisible(true);
    }//GEN-LAST:event_btn_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TempMenu main = new TempMenu();
                main.setLocationRelativeTo(null);
                main.setResizable(false);
                main.setTitle("Nurse Menu");
                main.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logOut;
    private javax.swing.JButton btn_newPatient;
    private javax.swing.JButton btn_oldPatient;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Icon;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_maidsDef;
    private javax.swing.JLabel lbl_maidsDef1;
    private javax.swing.JLabel lbl_maidsDef2;
    private javax.swing.JLabel lbl_maidsDef3;
    // End of variables declaration//GEN-END:variables
}
